DROP TABLE IF EXISTS score_board;

CREATE TABLE score_board (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             points BIGINT,
                             mode VARCHAR(255),
                             username VARCHAR(255)
);